
all:

install:
	install -d ${DESTDIR}/usr/share/pixmaps
	install maemopaedia ${DESTDIR}/usr/share/pixmaps
	install -d ${DESTDIR}/usr/share/applications/hildon
	install maemopaedia.desktop ${DESTDIR}/usr/share/applications/hildon

clean:


