
all:

install:
	install -d ${DESTDIR}/opt/maemopaedia/bin
	install maemopaedia ${DESTDIR}/opt/maemopaedia/bin
	install -d ${DESTDIR}/usr/share/pixmaps
	install maemopaedia.png ${DESTDIR}/usr/share/pixmaps
	install -d ${DESTDIR}/usr/share/applications/hildon
	install maemopaedia.desktop ${DESTDIR}/usr/share/applications/hildon

clean:


