
all:

install:
	install -d ${DESTDIR}/opt/mawire/bin
	install mawire ${DESTDIR}/opt/mawire/bin
	install -d ${DESTDIR}/usr/share/pixmaps
	install mawire.png ${DESTDIR}/usr/share/pixmaps
	install -d ${DESTDIR}/usr/share/applications/hildon
	install mawire.desktop ${DESTDIR}/usr/share/applications/hildon

clean:


